default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
auth: &auth
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
development:
  <<: *auth
  database: Bikboo_development
test:
  <<: *auth
  database: Bikboo_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
