default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
auth: &auth
  <<: *default
  host: <%= ENV['DATABASE_HOST'] or "localhost" %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] or "admin" %>
development:
  <<: *auth
  database: HerokuApp_development
test:
  <<: *auth
  database: HerokuApp_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
